"""empty message

Revision ID: 82e3d4483882
Revises:
Create Date: 2023-07-01 20:20:26.204228

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82e3d4483882"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("internal_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("authors", sa.String(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("internal_id"),
    )
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("internal_id", sa.BigInteger(), nullable=True),
        sa.Column("book_id", sa.BigInteger(), nullable=True),
        sa.Column("quote", sa.String(), nullable=False),
        sa.Column("context", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("translation", sa.String(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("internal_id"),
    )
    op.create_index(op.f("ix_notes_book_id"), "notes", ["book_id"], unique=False)
    op.create_index(op.f("ix_notes_id"), "notes", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_book_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
